import {
  DataTableOverviewComponent,
  BasicUsageComponent,
  DataTableClientSideDataBindingComponent,
  ClientSideDataBindingComponent,
  DataTableServerSideDataBindingComponent,
  ServerSideDataBindingComponent,
  DataTableRealTimeDataBindingComponent,
  RealTimeDataBindingComponent,
  DataTablePaginationComponent,
  PaginationUsageComponent,
  DataTableColumnSortingComponent,
  ColumnSortingUsageComponent,
  DataTableFilteringComponent,
  FilterDropdownUsageComponent,
  FilterTextBoxUsageComponent,
  DataTableResizableComponent,
  ColumnResizableUsageComponent,
  DataTablePersistDataComponent,
  DataPersistenceUsageComponent,
  DataTableSubstituteRowsComponent,
  WithSubstituteRowsUsageComponent,
  WithoutSubstituteRowsUsageComponent,
  DataTableLoadingSpinnerComponent,
  LoadingSpinnerUsageComponent,
  DataTableCellTemplateComponent,
  CellTemplateUsageComponent,
  DataTableRowExpandTemplateComponent,
  RowExpandTemplateUsageComponent,
  DataTableLoadingSpinnerTemplateComponent,
  LoadingSpinnerTemplateUsageComponent,
  DataTableNoRecordsTemplateComponent,
  NoRecordsTemplateUsageComponent,
  DataTableLimitComponent,
  DataTableHeaderDetailsComponent,
  TableHeaderDetailsUsageComponent,
  DataTableResponsiveConfComponent,
  ResponsiveConfAllUsageComponent,
  ResponsiveConfWithoutWidthHeightUsageComponent,
  DataTableTranslationsComponent,
  DataTableTranslationsNoDataUsageComponent,
  DataTableTranslationsPaginationUsageComponent
} from './components';

import { DataStorageService } from './services/data-storage.service';

// Components
export const COMPONENTS = [
  DataTableOverviewComponent,
  BasicUsageComponent,
  DataTableClientSideDataBindingComponent,
  ClientSideDataBindingComponent,
  DataTableServerSideDataBindingComponent,
  ServerSideDataBindingComponent,
  DataTableRealTimeDataBindingComponent,
  RealTimeDataBindingComponent,
  DataTablePaginationComponent,
  PaginationUsageComponent,
  DataTableColumnSortingComponent,
  ColumnSortingUsageComponent,
  DataTableFilteringComponent,
  FilterDropdownUsageComponent,
  FilterTextBoxUsageComponent,
  DataTableResizableComponent,
  ColumnResizableUsageComponent,
  DataTablePersistDataComponent,
  DataPersistenceUsageComponent,
  DataTableSubstituteRowsComponent,
  WithSubstituteRowsUsageComponent,
  WithoutSubstituteRowsUsageComponent,
  DataTableLoadingSpinnerComponent,
  LoadingSpinnerUsageComponent,
  DataTableCellTemplateComponent,
  CellTemplateUsageComponent,
  DataTableRowExpandTemplateComponent,
  RowExpandTemplateUsageComponent,
  DataTableLoadingSpinnerTemplateComponent,
  LoadingSpinnerTemplateUsageComponent,
  DataTableNoRecordsTemplateComponent,
  NoRecordsTemplateUsageComponent,
  DataTableLimitComponent,
  DataTableHeaderDetailsComponent,
  TableHeaderDetailsUsageComponent,
  DataTableResponsiveConfComponent,
  ResponsiveConfAllUsageComponent,
  ResponsiveConfWithoutWidthHeightUsageComponent,
  DataTableTranslationsComponent,
  DataTableTranslationsNoDataUsageComponent,
  DataTableTranslationsPaginationUsageComponent
];

// Services
export const SERVICES = [
  DataStorageService
];
