import {
  DropdownOverviewComponent,
  BasicUsageComponent,
  ClientSideDataBindingComponent,
  DropdownClientSideDataBindingComponent,
  ServerSideDataBindingComponent,
  DropdownServerSideDataBindingComponent,
  RealTimeDataBindingComponent,
  DropdownRealTimeDataBindingComponent,
  ItemGroupingUsageComponent,
  DropdownItemGroupingComponent,
  FilteringUsageComponent,
  DropdownFilteringComponent,
  MultiItemSelectionUsageComponent,
  SingleItemSelectionUsageComponent,
  SingleToggleItemSelectionUsageComponent,
  ItemSelectionWithAllOptionsUsageComponent,
  DropdownItemSelectionComponent,
  DataLimitUsageComponent,
  DropdownLimitComponent,
  DisablingUsageComponent,
  DropdownDisablingComponent,
  ItemDisablingUsageComponent,
  DropdownItemDisablingComponent
} from './components';

// Components
export const COMPONENTS = [
  DropdownOverviewComponent,
  BasicUsageComponent,
  ClientSideDataBindingComponent,
  DropdownClientSideDataBindingComponent,
  ServerSideDataBindingComponent,
  DropdownServerSideDataBindingComponent,
  RealTimeDataBindingComponent,
  DropdownRealTimeDataBindingComponent,
  ItemGroupingUsageComponent,
  DropdownItemGroupingComponent,
  FilteringUsageComponent,
  DropdownFilteringComponent,
  MultiItemSelectionUsageComponent,
  SingleItemSelectionUsageComponent,
  SingleToggleItemSelectionUsageComponent,
  ItemSelectionWithAllOptionsUsageComponent,
  DropdownItemSelectionComponent,
  DataLimitUsageComponent,
  DropdownLimitComponent,
  DisablingUsageComponent,
  DropdownDisablingComponent,
  ItemDisablingUsageComponent,
  DropdownItemDisablingComponent
];
