export interface Column {
  id: string;
  title: string;
  sortable: boolean;
  sortPriority: number;
  sortOrder: 'asc'| 'desc' | '';
  filterable: boolean;
  resizeable: boolean;
  resizeMinLimit: string;
  displayTrackBy: string;
  filterTrackBy: string;
  sortTrackBy: string;
  cssClass: string;
  width: string;
  visible: boolean;
  showInColumnSelector: boolean;
  filterMode: 'text' | 'dropdown';
  textFilterPlaceholder: string;
  textFilterShowClearButton: boolean;
  textFilterValue: any;
  showDropdownFilter: boolean;
  dropdownFilterMenuPosition: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
  dropdownFilterSelectMode: 'multi' | 'single' | 'single-toggle';
  dropdownFilterSearchable: boolean;
  dropdownFilterSearchDebounceTime: number;
  dropdownFilterSearchDebounce: boolean;
  dropDownFilterShowOptionSelectCheckbox: boolean;
  dropdownFilterWrapDisplaySelectLimit: number;
  dropdownFilterGroupByField: string;
  dropdownFilterShowSelectedOptionRemoveButton: boolean;
  dropdownFilterShowClearSelectionButton: boolean;
  dropdownFilterMenuWidth: number;
  dropdownFilterMenuHeight: number;
  dropdownFilterMultiSelectOptionMaxWidth: number;
  dropdownFilterCloseMenuOnSelect: boolean;
  dropdownFilterDynamicDimensionCalculation: boolean;
  dropdownFilterDynamicWidthRatio: number;
  dropdownFilterDynamicHeightRatio: number;
  dropdownFilterSelectTrackBy: string;
  dropdownFilterDisplayTrackBy: string;
  dropdownFilterDisabledTrackBy: string;
}
