export interface Store {
  progress: {
    isLoading: boolean;
    isInitialized: boolean;
  };
  config: {
    id: string;
    title: string;
    width: string;
    minContentWidth: string;
    minContentHeight: string;
    contentHeight: string;
    multiColumnSortable: boolean;
    showRefreshButton: boolean;
    showSpinner: boolean;
    statePersist: boolean;
    statePersistMode: 'local-storage' | 'session-storage';
    filterDebounce: boolean;
    filterDebounceTime: number;
    paginate: boolean;
    showSubstituteRows: boolean;
    infiniteScrollable: boolean;
    scrollViewDistanceRatio: number;
    showAutoIndex: boolean;
    autoIndexColumnTitle: string;
    autoIndexColumnWidth: string;
    showColumnSelector: boolean;
    columnSelectorWidth: string;
    translations: {
      paginationLimit: string;
      paginationRange: string;
      noDataMessageBody: string;
      noDataMessageHeader: string;
    }
    rowSelectable: boolean;
    rowSelectMode: 'single' | 'multi' | 'single-toggle';
    showRowSelectCheckbox: boolean;
    showRowSelectAllCheckbox: boolean;
    selectOnClick: boolean;
    rowSelectorColumnWidth: string;
    selectedRows: any[];
    selectTrackBy: string;
    expandOnClick: boolean;
    expanderColumnWidth: string;
    showExpanderLoadingSpinner: boolean;
  };
  expandableRows: {
    isEnabled: boolean;
    expandOnClick: boolean;
    columnWidth: string;
    showLoadingSpinner: boolean;
  };
  columns: Array<{
    id: string;
    title: string;
    sortable: boolean;
    sortPriority: number;
    sortOrder: 'asc'| 'desc' | '';
    filterable: boolean;
    resizeable: boolean;
    resizeMinLimit: string;
    displayTrackBy: string;
    filterTrackBy: string;
    sortTrackBy: string;
    cssClass: string;
    width: string;
    visible: boolean;
    showInColumnSelector: boolean;
    filterMode: 'text' | 'dropdown';
    textFilterPlaceholder: string;
    textFilterShowClearButton: boolean;
    textFilterValue: any;
    showDropdownFilter: boolean;
    dropdownFilterMenuPosition: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
    dropdownFilterSelectMode: 'multi' | 'single' | 'single-toggle';
    dropdownFilterSearchable: boolean;
    dropdownFilterSearchDebounceTime: number;
    dropdownFilterSearchDebounce: boolean;
    dropDownFilterShowOptionSelectCheckbox: boolean;
    dropdownFilterWrapDisplaySelectLimit: number;
    dropdownFilterGroupByField: string;
    dropdownFilterShowSelectedOptionRemoveButton: boolean;
    dropdownFilterShowClearSelectionButton: boolean;
    dropdownFilterMenuWidth: number;
    dropdownFilterMenuHeight: number;
    dropdownFilterMultiSelectOptionMaxWidth: number;
    dropdownFilterCloseMenuOnSelect: boolean;
    dropdownFilterDynamicDimensionCalculation: boolean;
    dropdownFilterDynamicWidthRatio: number;
    dropdownFilterDynamicHeightRatio: number;
    dropdownFilterSelectTrackBy: string;
    dropdownFilterDisplayTrackBy: string;
    dropdownFilterDisabledTrackBy: string;
  }>;
  data: {
    offset: number;
    limit: number;
    page: number;
    count: number;
    rows: Array<{
      id: string;
      item: any;
      selected: boolean;
      disabled: boolean;
      color: string;
      cssClass: string;
      tooltip: string;
      index: number;
      expanded: boolean;
      dataLoaded: boolean;
    }>;
    loadOnInit: boolean;
  };
}
